# Generated by Django 4.1.2 on 2023-04-05 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal', models.FileField(upload_to='images')),
            ],
            options={
                'verbose_name': 'Criminal',
                'verbose_name_plural': 'Criminal',
            },
        ),
        migrations.CreateModel(
            name='User_birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'User_birth',
                'verbose_name_plural': 'User_birth',
            },
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('orga_of_education', models.CharField(max_length=255)),
                ('year_of_graduation', models.FloatField(default=False)),
                ('specialist_certificate', models.FileField(upload_to='')),
                ('birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info1.user_birth')),
            ],
            options={
                'verbose_name': 'User_info',
                'verbose_name_plural': 'User_info',
            },
        ),
        migrations.CreateModel(
            name='User_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('organizations', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('experience', models.FloatField(default=False)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info1.user_info')),
            ],
            options={
                'verbose_name': 'User_work',
                'verbose_name_plural': 'User_works',
            },
        ),
        migrations.CreateModel(
            name='User_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_name',
                'verbose_name_plural': 'User_names',
            },
        ),
        migrations.AddField(
            model_name='user_birth',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info1.user_name'),
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.FileField(upload_to='images')),
                ('experience', models.FloatField(default=False)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info1.user_work')),
            ],
            options={
                'verbose_name': 'Practice',
                'verbose_name_plural': 'Practices',
            },
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info1.criminal')),
            ],
            options={
                'verbose_name': 'Medical',
                'verbose_name_plural': 'Medical',
            },
        ),
        migrations.AddField(
            model_name='criminal',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info1.practice'),
        ),
    ]
